'/android-training': '/training'
'/android': '/services'
'/enterprise-consulting-business-developer-app-iphone-ipad': '/training'
'/hire-us': '/services'
'/intro': '/about'
'/ios-development-training-course-melbourne-and-sydney': '/training'
'/ios-training-course-outline': '/training'
'/ios': '/services'
'/iphone-developer-training': '/training'
'/mobile-development': '/services'
'/services/enterprise-consulting-business-developer-app-iphone-ipad': '/services'
'/we-do': '/about'
'/we-do/enterprise-consulting-business-developer-app-iphone-ipad': '/about'
'/why-we-do-what-we-do': '/about'
'/wp-content/uploads/2011/02/Workshop_outline.pdf': '/pdf/workshop-outline.pdf'